name: stoicwallpaper
description: A new Flutter project.

publish_to: "none"

version: 2.1.0+18

environment:
  sdk: ">=2.18.0"

dependencies:
  android_alarm_manager_plus: ^3.0.4
  android_power_manager: ^1.0.0
  app_settings: ^5.1.1
  awesome_dialog: 2.0.0
  build_runner: ^2.4.7
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.6
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  external_path: ^1.0.3
  firebase_auth: 4.15.3
  firebase_core: 2.24.2
  firebase_storage: 11.5.6
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_downloader: ^1.11.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_local_notifications: 11.0.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_wallpaper_manager: ^0.0.4
  font_awesome_flutter: ^10.6.0
  google_mobile_ads: ^4.0.0
  google_sign_in: ^5.3.3
  hive: ^2.1.0
  hive_flutter: 1.1.0
  hive_generator: ^1.1.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.5
  in_app_purchase: ^0.5.2
  intl: ^0.19.0
  launch_review: ^3.0.1
  open_file_safe: ^3.2.3
  permission_handler: ^11.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.1
  uuid: ^4.3.1
  wallpaper: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.3.8

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
  android: true


flutter_icons:
  android: true
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - temp/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

