name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # paginate_firestore: ^1.0.3+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3
  path_provider: ^2.0.2
  permission_handler: ^11.3.1
  intl: ^0.19.0
  # ext_storage: ^2.0.0
  external_path: ^1.0.3
  flutter_downloader: ^1.4.4
  cloud_firestore: ^4.0.0
  font_awesome_flutter: ^10.7.0
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.2
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.0
  # connectivity: ^0.4.5+3
  cached_network_image: ^3.3.1
  launch_review: 3.0.1
  awesome_dialog: ^3.2.0
  onesignal_flutter: ^5.1.4
  firebase_analytics: ^10.0.0
  firebase_core: ^2.2.0
  shimmer: ^3.0.0
  firebase_admob: 0.11.2 #google_mobile_ads can be used as alternative
  # facebook_audience_network: ^0.5.0
  # fzwallpaper: ^1.0.3 //using async wallpaper because fzwallpaper 
  async_wallpaper: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.3

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.0


  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    
    - assets/images/icon.png
    - assets/images/splash.png
 
  fonts:



    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
